name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_ADDRESS }}
          username: github-deploy-user
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            if [ -d /home/prostynya ]; then
              rm -rf /home/prostynya
            fi
            git clone -b main --single-branch https://github.com/Merzlikin-Matvey/Prostynya.git /home/prostynya
            cd /home/prostynya
            docker-compose up --build -d